### ISSUE TITLE
Request: option for "pretty" JSON?

### ISSUE THREAD

**Issue by kevmoo** [google/built_json.dart#39]
Having more canonical, "pretty" JSON is nice – especially when saving to disk or interoperating with non-Dart systems.

Is that explicitly a non-Goal?

**Comment by davidmorgan** [comment]
Different formats is certainly a possibility.

In particular if there's a standard format that's powerful enough it would definitely make sense to add it. The problem is what to do when you don't know ahead of time the type you're deserializing, for example the test "BuiltMap with object keys" here:

https://github.com/google/built_json.dart/blob/master/built_json/test/built_map_serializer_test.dart#L208

Then we need some way of encoding the name of the type as well as the contents.

An alternative would be to say "you can only use this serialization method when you know all the types fully" ... but then, that would hopefully only be used for iterop. I think it's quite important to allow flexibility in precisely which types you're serializing -- that's what allows it to serialize object models.

Thoughts?

**Comment by davidmorgan** [comment]
Moved this issue here: https://github.com/google/built_value.dart/issues/65
